deadmedia/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from deadsource import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #url(r'^admin/', admin.site.urls),

    url(r'^$', views.show_videos, {'category': 'hot'}, name='main-page'),

    url(r'^(?P<category>(hot|adult|webm|mp4|all|hidden))/$',
        views.show_videos,
        {'sort': 'date', 'order': 'ordered'},
        name='videos-page'),

    url(r'^video/(?P<pk>[0-9]+)/(?P<command>(view|like|report))/$',
        views.user_video_commands,
        name='video-user-command'),

    url(r'^(?P<category>(hot|adult|webm|mp4|all|hidden))/sort/(?P<sort>(date|likes|views))/'
        r'(?P<order>(ordered|reversed))/$',
        views.show_videos,
        name='videos-page-sort'),

    url(r'^video/(?P<pk>[0-9]+)/(?P<command>(move/(hot|adult|webm|mp4))|delete|hide|reports/reset)/$',
        views.admin_video_commands,
        name='video-move-category'),

    url(r'^(?P<category>(hot|adult|webm|mp4|all|hidden))/category/delete$',
        views.category_delete,
        name='category-delete'),

    url(r'^reports/$', views.show_reported, name='reported-page'),
    url(r'^faq/$', views.show_faq, name='faq-page'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^login/$', views.login_view, name='login-page'),
    url(r'^accounts/login/$', views.login_view, name='login-page'),


    url(r'^bot/downloader/create/$', views.create_bot_downloader_view, name='create-downloader-bot'),
    url(r'^bot/inspector/create/$', views.create_bot_inspector_view, name='create-inspector-bot'),

    url(r'^bot/create/remover$', views.create_bot_remover_view, name='create-bot-remover'),

    #url(r'^page/admin/$', views.show_admin_page, name='page-admin'),
    url(r'^delete/$', views.delete_all_videos, name='delete-all'),

    url(r'^newadmin$', views.new_admin, name='page-admin-new'),
    url(r'^videos/size$', views.get_videos_size_in_db, name='page-admin-videos-size'),
    url(r'^videos/count$', views.get_videos_count_in_db, name='page-admin-videos-count'),
    url(r'^error404$', views.handler404, name='error404-page'),
    url(r'^error500$', views.handler404, name='error500-page'),

    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),

    url(r'^test$', views.test, name='test'),

    url(r'^logs/(?P<file>.*)$',
        views.show_logs,
        name='show-logs'),


    #url(r'^tasks/', include('taskmanager.urls')),
    url(r'^tasks/', include('deadtasks.urls', namespace='tasks')),
    url(r'^.*$', views.handler404),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'webms.views.handler404'

deadtasks/urls.py
from django.conf.urls import url
from . import views

app_name = 'tasks'
urlpatterns = [
    url(r'^create/d/$', views.create_task_2ch_downloader_view, name='create-download'),
    url(r'^create/r/$', views.create_task_old_remover_view, name='create-remove'),

    url(r'^(?P<task_type>(r|d))/(?P<pk>[0-9]+)/(?P<command>(activate|deactivate|delete))/$',
        views.tasks_commands,
        name='commands'),

    url(r'^status/$', views.tasks_status_view, name='status'),
    url(r'^test/$', views.test),
]

deadsource/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
import logging
import os
from functools import wraps

import requests
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import *
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from requests.exceptions import ConnectionError

from deadsource.utils.logs_module import log_critical_decorator
from .forms import VideoDeleteForm, BotTaskForm, BotTaskRemoveForm, BotTaskInspectForm
from .models import Video, BotTask
from .utils import paginator_module
from .utils.bot_module import (
    ThreadDownloader,
    VideoRemover,
)
from .utils.categorys_handler_module import (
    remove_all_videos_from_category,
)
from .utils.logs_module import get_logs_from_file
from .utils.video_handler_module import delete_video_by_db_object

logger = logging.getLogger("deadsource")


@log_critical_decorator(logger)
def show_videos(request,
                category='webm',
                sort='date',
                order='ordered'):
    videos_filters = "video_status = 'Video is downloaded'"
    page_content = {'is_authenticated': request.user.is_authenticated()}
    sort_revert = not order == 'reversed'

    if category == 'webm':
        videos_filters += " and is_webm = 1"
        page_content['category_name'] = 'webm'
        page_content['hide_videos_link'] = 'category-hide-webm'
        page_content['delete_videos_link'] = 'category-delete-webm'

    elif category == 'mp4':
        videos_filters += " and is_mp4 = 1"
        page_content['category_name'] = 'mp4'
        page_content['hide_videos_link'] = 'category-hide-mp4'
        page_content['delete_videos_link'] = 'category-delete-mp4'

    elif category == 'adult':
        videos_filters += " and is_adult = 1"
        page_content['category_name'] = 'adult'
        page_content['hide_videos_link'] = 'category-hide-adult'
        page_content['delete_videos_link'] = 'category-delete-adult'

    elif category == 'hot':
        videos_filters += " and is_hot = 1"
        page_content['category_name'] = 'hot'
        page_content['hide_videos_link'] = 'category-hide-hot'
        page_content['delete_videos_link'] = 'category-delete-hot'

    else:
        return redirect('error404-page')

    if sort == 'date':
        videos_order = 'added_date DESC' if sort_revert else 'added_date ASC'
        page_content['current_filter_name'] = 'Newest'

    elif sort == 'likes':
        videos_order = 'video_likes DESC' if sort_revert else 'video_likes ASC'
        page_content['current_filter_name'] = 'Hottest'

    elif sort == 'views':
        videos_order = 'video_views DESC' if sort_revert else 'video_views ASC'
        page_content['current_filter_name'] = 'Most Viewed'


    else:
        return redirect('error404-page')

    videos = paginator_module.get_filtered_and_sorted_videos_page(request, videos_filters, videos_order)

    page_content['videos'] = videos
    return render(request, 'videos_page.html', page_content)

@log_critical_decorator(logger)
def show_faq(request):
    return render(request,
                  'faq_page.html',
                  {
                      'category_name': 'faq',
                      'is_authenticated': request.user.is_authenticated(),
                  })

@log_critical_decorator(logger)
@login_required
def show_all(request):
    list_of_grouped_videos = zip(
        *[iter(
            Video.objects.all().filter().order_by('-added_date'))] * 4)

    page = request.GET.get('page', 1)
    paginator = Paginator(list_of_grouped_videos, 3)

    try:
        videos = paginator.page(page)
    except PageNotAnInteger:
        videos = paginator.page(1)
    except EmptyPage:
        videos = paginator.page(paginator.num_pages)
    return render(request,
                  'videos_page.html',
                  {
                      'category_name': 'all',
                      'videos': videos,
                      'is_authenticated': request.user.is_authenticated(),
                  })

@log_critical_decorator(logger)
@login_required
def show_admin_page(request):
    bot_downloader = ThreadDownloader()
    bot_remover = VideoRemover()

    if request.method == 'POST':
        form = VideoDeleteForm(request.POST)

        if form.is_valid():
            video = get_object_or_404(Video, pk=int(form.cleaned_data['storage_name']))
            video.delete()
            return redirect('page-admin-new')

    else:
        form = VideoDeleteForm()

    return render(request,
                  'admin_page.html',
                  {
                      'form': form,
                      'bot_downloader': bot_downloader.instance,
                      'bot_remover': bot_remover.instance,
                  })

@log_critical_decorator(logger)
@login_required
def show_reported(request):

     try:
         page = int(request.GET.get('page', -1))
     except Exception as e:
         logging.error('error!{} '.format(e))
         page = -1

     all_videos = Video.objects.all().filter(is_reported=True, video_status=Video.STATUS_DOWNLOADED).order_by('-added_date')
     sorted_videos = sorted(all_videos, key=lambda y: y.get_reports, reverse=True)
     videos = sorted_videos

     return render(request,
                   'reports_page.html',
                   {
                       'is_authenticated': request.user.is_authenticated(),
                       'videos': videos,
                   })

@log_critical_decorator(logger)
@login_required
def delete_all_videos(request):
    videos = Video.objects.all()

    for video in videos:
        delete_video_by_db_object(video)

    return redirect('page-admin-new')

@log_critical_decorator(logger)
@login_required
def new_admin(request):
    return render(request, 'admin.html')

@log_critical_decorator(logger)
def new_error(request):
    return render(request, 'error404_page.html')

@log_critical_decorator(logger)
@login_required
def new_admin(request):
    bot_downloader = ThreadDownloader()
    bot_remover = VideoRemover()



    if request.method == 'POST':
        form = VideoDeleteForm(request.POST)

        if form.is_valid():
            video = get_object_or_404(Video, pk=int(form.cleaned_data['storage_name']))
            delete_video_by_db_object(video)
            return redirect('page-admin-new')

    else:
        form = VideoDeleteForm()

    return render(request,
                  'admin.html',
                  {
                      'videos_weight': 'collecting',
                      'videos_count': 'collecting',
                      'form': form,
                      'bot_downloader': bot_downloader.instance,
                      'bot_remover': bot_remover.instance,
                      'is_authenticated': request.user.is_authenticated(),

                  })

@log_critical_decorator(logger)
@login_required
def get_videos_size_in_db(request):
    all_videos_weight = 0
    all_videos_weight_type = 'Kb'
    all_videos_in_db = Video.objects.all().filter(video_status=Video.STATUS_DOWNLOADED)

    for video in all_videos_in_db:
        all_videos_weight += int(video.video_size)

    if all_videos_weight > 999999999:
        all_videos_weight = all_videos_weight / 1000000000
        all_videos_weight_type = 'Tb'
    elif all_videos_weight > 999999:
        all_videos_weight = all_videos_weight / 1000000
        all_videos_weight_type = 'Gb'
    elif all_videos_weight > 999:
        all_videos_weight = all_videos_weight / 1000
        all_videos_weight_type = 'Mb'

    size = '{}{}'.format(all_videos_weight, all_videos_weight_type)

    return HttpResponse(size)

@log_critical_decorator(logger)
@login_required
def get_videos_count_in_db(request):
    all_videos_in_db = Video.objects.all().filter(video_status=Video.STATUS_DOWNLOADED)
    all_videos_count = all_videos_in_db.__len__()
    return HttpResponse(all_videos_count)

@log_critical_decorator(logger)
def handler404(request):
    return render(request, 'error404_page.html')

@log_critical_decorator(logger)
def logout_view(request):
    logout(request)
    return redirect('webm-page')

@log_critical_decorator(logger)
def check_recaptcha(view_func):
    @wraps(view_func)
    def _wrapped_view(request, *args, **kwargs):
        request.recaptcha_is_valid = None
        if request.method == 'POST':
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.RECAPTCHA_PRIVATE_KEY,
                'response': recaptcha_response
            }
            try:
                r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
                result = r.json()

                if result['success']:
                    request.recaptcha_is_valid = True
                else:
                    request.recaptcha_is_valid = False
                    messages.error(request, 'Invalid reCAPTCHA. Please try again.')

            except ConnectionError as e:
                request.recaptcha_is_valid = False
                messages.error(request, 'Can not check reCAPTCHA (connection error). Please try again.')
            except Exception as e:
                logging.error('check_recaptcha():{}'.format(e))
                request.recaptcha_is_valid = False
                messages.error(request, 'Unknown reCAPTCHA error. Please try again.')

        return view_func(request, *args, **kwargs)

    return _wrapped_view

@log_critical_decorator(logger)
@check_recaptcha
def login_view(request):
    logout(request)

    username = password = ''
    if request.method == 'POST' and request.recaptcha_is_valid:
        username = request.POST['username']
        password = request.POST['password']

deadsource/templates/admin_page.html
{% load staticfiles %}
<html>
  <head>

  </head>

  <body>
      <h1>Admin Page</h1>

      <a href="{% url 'page-admin-download-all' %}">Download all</a>
      <p><a href="{% url 'delete-all' %}">Empty</a></p>


      <form method="POST">
          <p><b>Delete video by url:</b></p>
          {% csrf_token %}
          {{ form.as_p }}
          <button type='submit'>Add</button>
      </form>

        <p><b>Bot downloader:</b><br \>
            Status:
            {% if bot_downloader.is_working %}
                Running
            {% else %}
                {% if bot_downloader.last_thread.is_alive %}
                    Finishing
                {% else %}
                    Stopped
                {% endif %}
            {% endif %}

        <p><a href="{% url 'page-admin-download-start-bot' %}"><button>Start downloader bot</button></a></p>
        <p><a href="{% url 'page-admin-download-stop-bot' %}"><button>Stop downloader bot</button></a></p>

          <p><b>Bot remover:</b><br \>
            Status:
            {% if bot_remover.is_working %}
                Running
            {% else %}
                {% if bot_remover.last_thread.is_alive %}
                    Finishing
                {% else %}
                    Stopped
                {% endif %}
            {% endif %}

        <p><a href="{% url 'page-admin-remove-start-bot' %}"><button>Start remover bot</button></a></p>
        <p><a href="{% url 'page-admin-remove-stop-bot' %}"><button>Stop remover bot</button></a></p>

  </body>
</html>

deadsource/templates/base_categories_menu.html
{% extends 'base_background.html' %} {% block background_content %}{% load static %} {% if is_authenticated %}
<ul class="admin-special-menu clearfix">
    <li><a href="{% url 'main-page' %}">Home</a></li>
    <li><a href="{% url 'page-admin-new' %}">ControlPanel</a></li>
    <li><a href="{% url 'tasks:status' %}">Status</a></li>
    <li><a href="{% url 'reported-page' %}">Report</a></li>
    <li><a href="{% url 'logout' %}">Sign out <i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
</ul>
{% endif %}

<div class="container">
    <div class="category">
        <div class="category-title">
            <a href="/"><img src="{% static 'img/logo_0.png' %}" class="logo" width="220px"></a>
        </div>
    </div>
</div>
<!--    menu-->
<nav class="menu clearfix">
    <!--    <a href="/" class="menu-logo-img"><img src="{% static 'img/logo_0.png' %}" height="26px" class="logo-mobile"></a>-->
    <!--            <span class="menu-logo">deadmedia</span>-->
    <a id="menu-trigger-btn">
                <i class="fa fa-bars" aria-hidden="true"></i>
            </a>
    <ul>
        <!--menu elements-->
        <li><a href="{% url 'videos-page' category='hot' %}"><i class="fa fa-rocket" aria-hidden="true"></i>Hot</a></li>
        {% if is_authenticated %}
        <li><a href="{% url 'videos-page' category='adult' %}"><i class="fa fa-smile-o" aria-hidden="true"></i>Adult</a></li>
        {% endif %}
        <li><a href="{% url 'videos-page' category='webm' %}" class="active"><i class="fa fa-globe" aria-hidden="true"></i>Random</a></li>
        <li><a href="{% url 'videos-page' category='mp4' %}"><i class="fa fa-mobile" aria-hidden="true"></i>.mp4</a></li>
        <li><a href="{% url 'faq-page' %}"><i class="fa fa-info" aria-hidden="true"></i>FAQ</a></li>
        <!--menu elements end-->
        <!--admin sign out-->
        {% if is_authenticated %}
        <hr>
        <li class="mobile-only"><a href="{% url 'main-page' %}">Home</a></li>
        <li class="mobile-only"><a href="{% url 'page-admin-new' %}">ControlPanel</a></li>
        <li class="mobile-only"><a href="{% url 'tasks:status' %}">Status</a></li>
        <li class="mobile-only"><a href="{% url 'reported-page' %}">Report</a></li>
        <li class="mobile-only"><a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Sign out</a></li>
        {% endif %}
        <!--admin logout ending-->
    </ul>
</nav>
<!--    menu ending-->
<div class="container">
    <div class="menu-special-border"></div>
</div>

{% block script_content %} {% endblock %} {% block content %} {% endblock %} {% endblock %}

deadsource/templates/base_categorys_menu.html
{% extends 'base_background.html' %} {% block background_content %}{% load static %}
        <div class="container">
            <div class="category">
                <div class="category-title">
                    <!--
                    <span class="title">DM</span>
                    <span class="title-sub">{{category_name}}</span>
-->
                    <a href="/"><img src="{% static 'img/logo.png' %}" class="logo" width="320px"></a>
                </div>
            </div>
        </div>
        <!--    menu-->
        <nav class="menu clearfix">
            <a href="/" class="menu-logo-img"><img src="{% static 'img/logo_pride.png' %}" height="26px"></a>
            <!--            <span class="menu-logo">deadmedia</span>-->
            <a id="menu-trigger-btn">
                <i class="fa fa-bars" aria-hidden="true"></i>
            </a>
            <ul>
                <!--menu elements-->
                <li><a href="{% url 'hot-page' %}"><i class="fa fa-bolt" aria-hidden="true"></i>Hot</a></li>
                <li><a href="{% url 'adult-page' %}"><i class="fa fa-smile-o" aria-hidden="true"></i>Adult</a></li>
                <li><a href="{% url 'webm-page' %}" class="active"><i class="fa fa-wheelchair-alt" aria-hidden="true"></i>Webm</a></li>
                <li><a href="{% url 'mp4-page' %}"><i class="fa fa-mobile" aria-hidden="true"></i>Mp4</a></li>
                <li><a href="{% url 'faq-page' %}"><i class="fa fa-info" aria-hidden="true"></i>FAQ</a></li>
                <!--menu elements end-->
                <!--admin sign out-->
                {% if is_authenticated %}
                <li class="admin-sign-out-mobile"><a href="{% url 'logout' %}">Sign out</a></li>
                {% endif %}
                <!--admin logout ending-->
            </ul>
        </nav>
        <!--    menu ending-->

        <div class="container">
            <div class="menu-special-border"></div>
        </div>

        {% block content %}
        {% endblock %}

{% endblock %}

deadsource/templates/create_bot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>{{form.bot_task}}</p>
        {% for error in  form.bot_task.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Find threads with words: <input name="with_words" type="text"></p>
        {% for error in  form.with_words.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Ignore threads with words: <input name="without_words" type="text"></p>
        {% for error in  form.without_words.errors %}
            <h1>error</h1>
        {% endfor %}
        <p>Set adult category: <input name="is_adult" type="checkbox"></p>
        {% for error in  form.is_adult.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set music category: <input name="is_music" type="checkbox"></p>
        {% for error in  form.is_music.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set webm category: <input name="is_webm" type="checkbox"></p>
        {% for error in  form.is_webm.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set hot category: <input name="is_hot" type="checkbox"></p>
        {% for error in  form.is_hot.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set mp4 category: <input name="is_mp4" type="checkbox"></p>
        {% for error in  form.is_mp4.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Interval between iters: <input name="interval" type="number" value="0"></p>
        {% for error in  form.interval.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set working duration: <input name="is_max_time" type="checkbox"></p>
        {% for error in  form.is_max_time.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Working duration: <input name="working_time" type="number" value="1"></p>
        {% for error in  form.working_time.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set max iter: <input name="is_max_iter" type="checkbox"></p>
        {% for error in  form.is_max_iter.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Max iters count: <input name="iters_to_do" type="number" value="1"></p>
        {% for error in  form.iters_to_do.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Count of videos per iter: <input name="max_videos_count" type="number"></p>
        {% for error in  form.max_videos_count.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Formats to download: <input name="video_formats" type="text"></p>
        {% for error in  form.video_formats.errors %}
            <h1>{{error}}</h1>
        {% endfor %}


        <button class="btn btn-sm btn-default btn-block" type="submit">Create bot</button>
    </form>
</body>
</html>

deadsource/templates/create_inspect_bot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        <p>INSPECT BOT</p>
        {% csrf_token %}
        <p>Interval between iters: <input name="interval" type="number" value="0"></p>
        {% for error in  form.interval.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set working duration: <input name="is_max_time" type="checkbox"></p>
        {% for error in  form.is_max_time.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Working duration: <input name="working_time" type="number" value="1"></p>
        {% for error in  form.working_time.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set max iter: <input name="is_max_iter" type="checkbox"></p>
        {% for error in  form.is_max_iter.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Max iters count: <input name="iters_to_do" type="number" value="1"></p>
        {% for error in  form.iters_to_do.errors %}
            <h1>{{error}}</h1>
        {% endfor %}

        <button class="btn btn-sm btn-default btn-block" type="submit">Create bot</button>
    </form>
</body>
</html>

deadsource/templates/create_remove_bot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        <p>REMOVE BOT</p>
        {% csrf_token %}
        <p>Set ignore_time: <input name="ignore_time" type="number"></p>
        {% for error in  form.ignore_time.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set adult category: <input name="is_adult" type="checkbox"></p>
        {% for error in  form.is_adult.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set music category: <input name="is_music" type="checkbox"></p>
        {% for error in  form.is_music.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set webm category: <input name="is_webm" type="checkbox"></p>
        {% for error in  form.is_webm.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set hot category: <input name="is_hot" type="checkbox"></p>
        {% for error in  form.is_hot.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set mp4 category: <input name="is_mp4" type="checkbox"></p>
        {% for error in  form.is_mp4.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Interval between iters: <input name="interval" type="number" value="0"></p>
        {% for error in  form.interval.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set working duration: <input name="is_max_time" type="checkbox"></p>
        {% for error in  form.is_max_time.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Working duration: <input name="working_time" type="number" value="1"></p>
        {% for error in  form.working_time.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Set max iter: <input name="is_max_iter" type="checkbox"></p>
        {% for error in  form.is_max_iter.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Max iters count: <input name="iters_to_do" type="number" value="1"></p>
        {% for error in  form.iters_to_do.errors %}
            <h1>{{error}}</h1>
        {% endfor %}
        <p>Count of videos per iter: <input name="max_videos_count" type="number"></p>
        {% for error in  form.max_videos_count.errors %}
            <h1>{{error}}</h1>
        {% endfor %}


        <button class="btn btn-sm btn-default btn-block" type="submit">Create bot</button>
    </form>
</body>
</html>

deadsource/templates/faq.html
<!DOCTYPE html>

{% load static %}
<html>
<head lang="en">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width" />
    <title>WEBM</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
<body>
    <div class="container">
        <div class="category">
            <div class="category-title">
                <span class="title">24FAQ</span>
                <span class="title-sub">webm</span>
            </div>
        </div>
    </div>
    <!--admin sign out-->
    <a href="#" class="admin-sign-out">Sign out <i class="fa fa-sign-out" aria-hidden="true"></i></a>
    <!--admin logout ending-->
    <!--    menu-->
    <nav class="menu">
        <a href="#" class="menu-trigger clearfix">
            <span class="menu-logo">Webm24</span>
            <i class="fa fa-bars" aria-hidden="true" id="menu-trigger-btn"></i>
        </a>
        <ul>
            <li><a href="#"><i class="fa fa-bolt" aria-hidden="true"></i>Hot</a></li>
            <li><a href="#"><i class="fa fa-smile-o" aria-hidden="true"></i>Adult</a></li>
            <li><a href="#" class="active"><i class="fa fa-wheelchair-alt" aria-hidden="true"></i>Webm</a></li>
            <li><a href="#"><i class="fa fa-mobile" aria-hidden="true"></i>Mp4</a></li>
            <li><a href="{% url 'site-faq' %}"><i class="fa fa-info" aria-hidden="true"></i>FAQ</a></li>
            <!--admin sign out-->
            <li class="admin-sign-out-mobile"><a href="#">Sign out</a></li>
            <!--admin logout ending-->
        </ul>
    </nav>
    <!--    menu ending-->

    <div class="container">
        <hr>
    </div>


    <div class="container">
    </div>

    <footer class="footer">
        <div class="container">
            <span class="copyright">Copyright &copy; 2017 deadmedia.us All rights reserved.</span>
        </div>
    </footer>
</body>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script src="{% static 'js/style.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/fullscreen.js' %}"></script>
<script src="{% static 'js/tippy.min.js' %}"></script>
</html>

deadsource/templates/logs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for log in logs %}
        {{log}}<br>
    {% empty %}
        Empty
    {% endfor %}
</body>
</html>